function [slider,editbox] = createUis(parent,nTotal,iteName)
slider = uicontrol('Parent',parent,'Style','slider','Position',[140,40,419,30],...
    'value',1, 'min',1, 'max',nTotal, 'SliderStep',[1/nTotal,10/nTotal]);
editbox = uicontrol('Parent',parent,'Style','edit','Position',[600,100,50,30],...
    'String','1', 'min',1, 'max',0,'FontSize',11);
bgcolor = parent.Color;

sPos = slider.Position;
editbox.Position = [sPos(1)+sPos(3)+200,sPos(2),50,30];
ePos = editbox.Position;

uicontrol('Parent',parent,'Style','text',...
    'Position',[sPos(1)+sPos(3)/2-125,sPos(2)-30,300,20],...
    'String',['drag the slider to change the ',iteName,' number'],...
    'BackgroundColor',bgcolor,'FontSize',11);
uicontrol('Parent',parent,'Style','text','Position',[sPos(1)-15,sPos(2)-5,10,30],...
    'String','1','BackgroundColor',bgcolor,'FontSize',11);
uicontrol('Parent',parent,'Style','text','Position',[sPos(1)+sPos(3)+5,sPos(2)-5,30,30],...
    'String',num2str(nTotal),'BackgroundColor',bgcolor,'FontSize',11);
uicontrol('Parent',parent,'Style','text','Position',[ePos(1)+ePos(3)/2-150,ePos(2)-30,300,20],...
    'String',['enter a number to change the ',iteName,' number'],'BackgroundColor',...
    bgcolor,'FontSize',11);
end

