function R = so3(alpha,beta,gamma)
%SO3 Summary of this function goes here
%   Detailed explanation goes here
R = [(1/2).*exp(1).^((sqrt(-1)*(-1)).*alpha+(sqrt(-1)*(-1)).*gamma).*( ...
  1+cos(beta)),(-1).*2.^(-1/2).*exp(1).^((sqrt(-1)*(-1)).*alpha).* ...
  sin(beta),(1/2).*exp(1).^((sqrt(-1)*(-1)).*alpha+sqrt(-1).*gamma) ...
  .*(1+(-1).*cos(beta));2.^(-1/2).*exp(1).^((sqrt(-1)*(-1)).*gamma) ...
  .*sin(beta),cos(beta),(-1).*2.^(-1/2).*exp(1).^(sqrt(-1).*gamma).* ...
  sin(beta);(1/2).*exp(1).^(sqrt(-1).*alpha+(sqrt(-1)*(-1)).*gamma) ...
  .*(1+(-1).*cos(beta)),2.^(-1/2).*exp(1).^(sqrt(-1).*alpha).*sin( ...
  beta),(1/2).*exp(1).^(sqrt(-1).*alpha+sqrt(-1).*gamma).*(1+cos( ...
  beta))];
end

