function E = gaussian_prof(in1,w0,k)
%GAUSSIAN_PROF
%    E = GAUSSIAN_PROF(IN1,W0,K)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    07-May-2018 14:32:25

r1 = in1(:,1);
r2 = in1(:,2);
r3 = in1(:,3);
if (r3 == 0.0)
    E = exp(-1.0./w0.^2.*(r1.^2+r2.^2));
else
    E = exp(-(1.0./w0.^2.*(r1.^2+r2.^2))./(1.0./k.^2.*r3.^2.*1.0./w0.^4.*4.0+1.0)).*exp(atan((r3.*1.0./w0.^2.*2.0)./k).*1i-k.*r3.*1i-(k.*(r1.^2+r2.^2).*5.0e-1i)./(r3.*(k.^2.*1.0./r3.^2.*w0.^4.*(1.0./4.0)+1.0))).*1.0./sqrt(1.0./k.^2.*r3.^2.*1.0./w0.^4.*4.0+1.0);
end
